spring.application.name=users

server.port=8020
spring.devtools.restart.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8010/eureka

# H2
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:microservices-users-db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Config server properties
spring.config.import=optional:configserver:http://localhost:8012
spring.cloud.config.name=config_server

# Actuator properties
management.endpoints.web.exposure.include=beans,mappings,health,httpexchanges
