spring.application.name=users

server.port=8020
spring.devtools.restart.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8010/eureka

# H2
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:microservices-users-db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Config server properties
spring.config.import=optional:configserver:http://localhost:8012
spring.cloud.config.name=config_server

# Actuator properties
management.endpoints.web.exposure.include=beans,mappings,health,httpexchanges,circuitbreakerevents
management.endpoint.health.access=read_only
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Feign client logger
logging.level.com.users.client.AddressesFeignClient=DEBUG

# Resilience4j properties
# The failure rate threshold (percentage) to transition the circuit breaker to an OPEN state.
# If 50% of the calls fail, the circuit breaker opens.
resilience4j.circuitbreaker.instances.address.failure-rate-threshold=50
# Enables automatic transition from OPEN to HALF-OPEN state after the wait duration.
resilience4j.circuitbreaker.instances.address.automatic-transition-from-open-to-half-open-enabled=true
# The duration the circuit breaker stays in the OPEN state before transitioning to HALF-OPEN.
resilience4j.circuitbreaker.instances.address.wait-duration-in-open-state=10s
# Defines the type of sliding window used.
# COUNT_BASED means the circuit breaker considers a fixed number of calls instead of a time-based window.
resilience4j.circuitbreaker.instances.address.sliding-window-type=COUNT_BASED
# The size of the sliding window.
# Since it's COUNT_BASED, it will track the last 2 calls.
resilience4j.circuitbreaker.instances.address.sliding-window-size=2
# The minimum number of calls required before the failure rate is calculated.
# Even if failures occur, the circuit breaker will not activate until at least 1 call has been made.
resilience4j.circuitbreaker.instances.address.minimum-number-of-calls=1
# The buffer size for event consumers (e.g., monitoring and logging).
# It determines how many events will be stored for processing.
resilience4j.circuitbreaker.instances.address.event-consumer-buffer-size=10