spring.application.name=address
server.port=8040
spring.devtools.restart.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8010/eureka

# Config server properties
spring.config.import=optional:configserver:http://localhost:8012
spring.cloud.config.name=config_server

# H2
spring.datasource.username=sa
spring.datasource.password=pass
spring.datasource.url=jdbc:h2:mem:microservices-address-db
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update