spring.application.name=gateway
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8010/eureka
#spring.cloud.gateway.discovery.locator.enabled=true

# Spring Cloud Gateway Routes
spring.cloud.gateway.routes[0].id=users-status-check
spring.cloud.gateway.routes[0].uri=lb://users
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/status/check
spring.cloud.gateway.routes[0].predicates[1]=Method=GET
#spring.cloud.gateway.routes[0].predicates[2]=Header=Authorization, Bearer (.*)
spring.cloud.gateway.routes[0].filters[0]=RemoveRequestHeader=Cookie
#spring.cloud.gateway.routes[0].filters[1]=RewritePath=/users/(?<segment>).*, /$\{segment}

spring.cloud.gateway.routes[1].id=account-status-check
spring.cloud.gateway.routes[1].uri=lb://account
spring.cloud.gateway.routes[1].predicates[0]=Path=/accounts/status/check
spring.cloud.gateway.routes[1].predicates[1]=Method=GET
spring.cloud.gateway.routes[1].filters[0]=RemoveRequestHeader=Cookie

spring.cloud.gateway.routes[2].id=users-create
spring.cloud.gateway.routes[2].uri=lb://users
spring.cloud.gateway.routes[2].predicates[0]=Path=/users
spring.cloud.gateway.routes[2].predicates[1]=Method=POST


spring.cloud.gateway.routes[3].id=users-login
spring.cloud.gateway.routes[3].uri=lb://users
spring.cloud.gateway.routes[3].predicates[0]=Path=/users/login
spring.cloud.gateway.routes[3].predicates[1]=Method=POST
spring.cloud.gateway.routes[3].filters[0]=RemoveRequestHeader=Cookie

spring.cloud.gateway.routes[4].id=users-h2-console
spring.cloud.gateway.routes[4].uri=lb://users
spring.cloud.gateway.routes[4].predicates[0]=Path=/users/h2-console
spring.cloud.gateway.routes[4].predicates[1]=Method=GET
spring.cloud.gateway.routes[4].filters[0]=RemoveRequestHeader=Cookie

spring.cloud.gateway.routes[5].id=users-actuator
spring.cloud.gateway.routes[5].uri=lb://users
spring.cloud.gateway.routes[5].predicates[0]=Path=/users/actuator/**
spring.cloud.gateway.routes[5].predicates[1]=Method=GET
spring.cloud.gateway.routes[5].filters[0]=RemoveRequestHeader=Cookie
spring.cloud.gateway.routes[5].filters[1]=RewritePath=/users/actuator/(?<segment>.*), /actuator/$\{segment}

spring.cloud.gateway.routes[6].id=address-status-check
spring.cloud.gateway.routes[6].uri=lb://address
spring.cloud.gateway.routes[6].predicates[0]=Path=/address/status/check
spring.cloud.gateway.routes[6].predicates[1]=Method=GET
spring.cloud.gateway.routes[6].filters[0]=RemoveRequestHeader=Cookie


# Config server properties
spring.config.import=optional:configserver:http://localhost:8012
spring.cloud.config.name=config_server

# Actuator properties
management.endpoint.gateway.access=unrestricted
management.endpoints.web.exposure.include=*