spring.application.name=eureka
server.port=8010
eureka.instance.hostname=localhost
# Set to false to prevent the Eureka server from registering itself
eureka.client.register-with-eureka=false
# Set to false because the Eureka server does not need to fetch registry information from itself
eureka.client.fetch-registry=false
# The service URL for the Eureka server where clients will register
# The ${server.port} will be replaced by the port specified for the Eureka server
eureka.client.service-url.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
